language: node_js
sudo: false

node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
  - node

matrix:
  # include:
    # - script: npm run test4
    #   node_js: "4"
    # - script: npm run test4
    #   node_js: "5"

  allow_failures:
    - env: NODEJS_VERSION=4
    - env: NODEJS_VERSION=5
